### ISSUE TITLE
Configuration error in Ubuntu 18 

### ISSUE THREAD

**Issue by meldiwin** [penn-graphics-research/ziran2020#1]
CMake Error: File /home/marwa/ziran2020/Scripts/git-pre-commit-hook does not exist.
CMake Error at Scripts/CMakeLists.txt:69 (configure_file):
  configure_file Problem configuring file

make: *** No targets specified and no makefile found.  Stop.

**Comment by squarefk** [comment]
This file was ignored for some unknown reason. I have uploaded it to the repo.
Thanks for your finding. Please post if there is you have any other issue with compiling.

**Comment by meldiwin** [comment]
Thanks so much! I am highly interested in this paper. I am hosting Soft robotics podcast and I am thinking of hosting you to discuss your paper, in the podcast we highlighted sometimes MPM methods is underrated, do you have an email address for contact?
