### ISSUE TITLE
Data.zip is missing

### ISSUE THREAD

**Issue by kentbarber** [penn-graphics-research/ziran2020#17]
The Data.zip file referred to in the readme is missing.

https://www.seas.upenn.edu/~cffjiang/research/ziran2020/Data.zip

**Comment by JoshWolper** [comment]
Thanks for pointing this out!! I just added a new link to Data.zip! It can now be found at: https://drive.google.com/file/d/1f22ObJmiq8H1_YObTz5BuE4IAWLQhyuB/view?usp=sharing
