### ISSUE TITLE
Error 2 in wsl ubuntu 18.04

### ISSUE THREAD

**Issue by jackylovechina** [penn-graphics-research/ziran2020#4]
[  9%] Built target spgrid
[ 18%] Built target partio
[ 18%] Built target format
[ 67%] Built target ziran
[ 68%] Building CXX object Lib/MPM/CMakeFiles/mpmdev.dir/instantiations/MpmSimulation2d.cpp.o
[ 69%] Building CXX object Lib/MPM/CMakeFiles/mpmdev.dir/instantiations/MpmSimulation2f.cpp.o
[ 70%] Building CXX object Lib/MPM/CMakeFiles/mpmdev.dir/instantiations/MpmSimulation3d.cpp.o
[ 71%] Building CXX object Lib/MPM/CMakeFiles/mpmdev.dir/instantiations/MpmSimulation3f.cpp.o
In file included from /home/yc/iqmpm/ziran2020/Lib/SPGrid/../Ziran/Math/Linear/DirectSolver.h:32:0,
                 from /home/yc/iqmpm/ziran2020/Lib/SPGrid/../MPM/MpmMultivarSystem.h:9,
                 from /home/yc/iqmpm/ziran2020/Lib/MPM/instantiations/../MpmSimulationBase.h:9,
                 from /home/yc/iqmpm/ziran2020/Lib/MPM/instantiations/../MpmSimulationBase.cpp:2,
                 from /home/yc/iqmpm/ziran2020/Lib/MPM/instantiations/MpmSimulation2d.cpp:2:
/home/yc/iqmpm/ziran2020/build/amgcl-src/amgcl/backend/vexcl.hpp:40:10: fatal error: vexcl/vector.hpp: No such file or directory
 #include <vexcl/vector.hpp>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /home/yc/iqmpm/ziran2020/Lib/SPGrid/../Ziran/Math/Linear/DirectSolver.h:32:0,
                 from /home/yc/iqmpm/ziran2020/Lib/SPGrid/../MPM/MpmMultivarSystem.h:9,
                 from /home/yc/iqmpm/ziran2020/Lib/MPM/instantiations/../MpmSimulationBase.h:9,
                 from /home/yc/iqmpm/ziran2020/Lib/MPM/instantiations/../MpmSimulationBase.cpp:2,
                 from /home/yc/iqmpm/ziran2020/Lib/MPM/instantiations/MpmSimulation3f.cpp:2:
/home/yc/iqmpm/ziran2020/build/amgcl-src/amgcl/backend/vexcl.hpp:40:10: fatal error: vexcl/vector.hpp: No such file or directory
 #include <vexcl/vector.hpp>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /home/yc/iqmpm/ziran2020/Lib/SPGrid/../Ziran/Math/Linear/DirectSolver.h:32:0,
                 from /home/yc/iqmpm/ziran2020/Lib/SPGrid/../MPM/MpmMultivarSystem.h:9,
                 from /home/yc/iqmpm/ziran2020/Lib/MPM/instantiations/../MpmSimulationBase.h:9,
                 from /home/yc/iqmpm/ziran2020/Lib/MPM/instantiations/../MpmSimulationBase.cpp:2,
                 from /home/yc/iqmpm/ziran2020/Lib/MPM/instantiations/MpmSimulation3d.cpp:2:
/home/yc/iqmpm/ziran2020/build/amgcl-src/amgcl/backend/vexcl.hpp:40:10: fatal error: vexcl/vector.hpp: No such file or directory
 #include <vexcl/vector.hpp>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /home/yc/iqmpm/ziran2020/Lib/SPGrid/../Ziran/Math/Linear/DirectSolver.h:32:0,
                 from /home/yc/iqmpm/ziran2020/Lib/SPGrid/../MPM/MpmMultivarSystem.h:9,
                 from /home/yc/iqmpm/ziran2020/Lib/MPM/instantiations/../MpmSimulationBase.h:9,
                 from /home/yc/iqmpm/ziran2020/Lib/MPM/instantiations/../MpmSimulationBase.cpp:2,
                 from /home/yc/iqmpm/ziran2020/Lib/MPM/instantiations/MpmSimulation2f.cpp:2:
/home/yc/iqmpm/ziran2020/build/amgcl-src/amgcl/backend/vexcl.hpp:40:10: fatal error: vexcl/vector.hpp: No such file or directory
 #include <vexcl/vector.hpp>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
Lib/MPM/CMakeFiles/mpmdev.dir/build.make:350: recipe for target 'Lib/MPM/CMakeFiles/mpmdev.dir/instantiations/MpmSimulation2d.cpp.o' failed
make[2]: *** [Lib/MPM/CMakeFiles/mpmdev.dir/instantiations/MpmSimulation2d.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
Lib/MPM/CMakeFiles/mpmdev.dir/build.make:422: recipe for target 'Lib/MPM/CMakeFiles/mpmdev.dir/instantiations/MpmSimulation3f.cpp.o' failed
make[2]: *** [Lib/MPM/CMakeFiles/mpmdev.dir/instantiations/MpmSimulation3f.cpp.o] Error 1
Lib/MPM/CMakeFiles/mpmdev.dir/build.make:398: recipe for target 'Lib/MPM/CMakeFiles/mpmdev.dir/instantiations/MpmSimulation3d.cpp.o' failed
make[2]: *** [Lib/MPM/CMakeFiles/mpmdev.dir/instantiations/MpmSimulation3d.cpp.o] Error 1
Lib/MPM/CMakeFiles/mpmdev.dir/build.make:374: recipe for target 'Lib/MPM/CMakeFiles/mpmdev.dir/instantiations/MpmSimulation2f.cpp.o' failed
make[2]: *** [Lib/MPM/CMakeFiles/mpmdev.dir/instantiations/MpmSimulation2f.cpp.o] Error 1
CMakeFiles/Makefile2:278: recipe for target 'Lib/MPM/CMakeFiles/mpmdev.dir/all' failed
make[1]: *** [Lib/MPM/CMakeFiles/mpmdev.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ZP-Z** [comment]
turn off amgcl cuda in Cmakelists

**Comment by jackylovechina** [comment]
thanks
