### ISSUE TITLE
anisofracture.cpp -make anisofracture -j8 compiling issue

### ISSUE THREAD

**Issue by meldiwin** [penn-graphics-research/ziran2020#7]
usr/include/tbb/atomic.h:21:141: note: #pragma message: TBB Warning: tbb/atomic.h is deprecated. For details, please see Deprecated Features appendix in the TBB reference manual.
 #pragma message("TBB Warning: tbb/atomic.h is deprecated. For details, please see Deprecated Features appendix in the TBB reference manual.")
                                                                                                                                             ^
/home/marwa/ziran2020/Projects/anisofracture/anisofracture.cpp:14:1: error: ‘define’ does not name a type; did you mean ‘rewind’?
 define dim 3
 ^~~~~~
 rewind
/home/marwa/ziran2020/Projects/anisofracture/anisofracture.cpp: In function ‘int main(int, char**)’:
/home/marwa/ziran2020/Projects/anisofracture/anisofracture.cpp:119:40: error: ‘dim’ was not declared in this scope
             AnisoFractureSimulation<T, dim> e(Python::implicit);
                                        ^~~
/home/marwa/ziran2020/Projects/anisofracture/anisofracture.cpp:119:40: note: suggested alternative: ‘div’
             AnisoFractureSimulation<T, dim> e(Python::implicit);
                                        ^~~
                                        div
/home/marwa/ziran2020/Projects/anisofracture/anisofracture.cpp:119:43: error: template argument 2 is invalid
             AnisoFractureSimulation<T, dim> e(Python::implicit);
                                           ^
/home/marwa/ziran2020/Projects/anisofracture/anisofracture.cpp:121:19: error: request for member ‘diff_test’ in ‘e’, which is of non-class type ‘int’
                 e.diff_test = true;
                   ^~~~~~~~~
/home/marwa/ziran2020/Projects/anisofracture/anisofracture.cpp:122:19: error: request for member ‘diff_test_perturbation_scale’ in ‘e’, which is of non-class type ‘int’
                 e.diff_test_perturbation_scale = diff_test_perturbation_scale;
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/marwa/ziran2020/Projects/anisofracture/anisofracture.cpp:124:15: error: request for member ‘logger’ in ‘e’, which is of non-class type ‘int’
             e.logger = LogWorker::initializeLogging();
               ^~~~~~
/home/marwa/ziran2020/Projects/anisofracture/anisofracture.cpp:128:52: error: no matching function for call to ‘ZIRAN::AnisoFractureInit3D<double>::AnisoFractureInit3D(int&, int&)’
             AnisoFractureInit3D<T> h(e, test_number);
                                                    ^
In file included from /home/marwa/ziran2020/Projects/anisofracture/anisofracture.cpp:9:0:
/home/marwa/ziran2020/Projects/anisofracture/AnisoFractureInit3D.h:41:5: note: candidate: ZIRAN::AnisoFractureInit3D<T>::AnisoFractureInit3D(ZIRAN::AnisoFractureSimulation<T, 3>&, int) [with T = double]
     AnisoFractureInit3D(AnisoFractureSimulation<T, dim>& sim, const int test_number)
     ^~~~~~~~~~~~~~~~~~~
/home/marwa/ziran2020/Projects/anisofracture/AnisoFractureInit3D.h:41:5: note:   no known conversion for argument 1 from ‘int’ to ‘ZIRAN::AnisoFractureSimulation<double, 3>&’
/home/marwa/ziran2020/Projects/anisofracture/AnisoFractureInit3D.h:26:7: note: candidate: constexpr ZIRAN::AnisoFractureInit3D<double>::AnisoFractureInit3D(const ZIRAN::AnisoFractureInit3D<double>&)
 class AnisoFractureInit3D : public AnisoFractureInitBase<T, 3> {
       ^~~~~~~~~~~~~~~~~~~
/home/marwa/ziran2020/Projects/anisofracture/AnisoFractureInit3D.h:26:7: note:   candidate expects 1 argument, 2 provided
/home/marwa/ziran2020/Projects/anisofracture/AnisoFractureInit3D.h:26:7: note: candidate: constexpr ZIRAN::AnisoFractureInit3D<double>::AnisoFractureInit3D(ZIRAN::AnisoFractureInit3D<double>&&)
/home/marwa/ziran2020/Projects/anisofracture/AnisoFractureInit3D.h:26:7: note:   candidate expects 1 argument, 2 provided
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-catch-value’
make[3]: *** [Projects/anisofracture/CMakeFiles/anisofracture.dir/build.make:63: Projects/anisofracture/CMakeFiles/anisofracture.dir/anisofracture.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:447: Projects/anisofracture/CMakeFiles/anisofracture.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:454: Projects/anisofracture/CMakeFiles/anisofracture.dir/rule] Error 2
make: *** [Makefile:227: anisofracture] Error 2

**Comment by JoshWolper** [comment]
Hmm could you please add the full command line input as well as the full output? unsure why it's not recognizing "define"

**Comment by meldiwin** [comment]
Hi Josh,

Many thanks it works now :) I closed the issue

Cheers,
Marwa
